import Head from "next/head";
import styled from "styled-components";

import FairWidget from "../modules/FairWidget";

const MainContainer = styled.main`
  width: 100vw;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
`;

// HOWDY THINK TEAM
// Below you will find a list of assumptions I made prior to working on the challenge.
// Hopefully my notes make sense. I ran out of coffee half way through this challenge so the last 30 mins were rough.

/**
 * **************************
 *     MADE ASSUMPTIONS
 * **************************
 *
 * #1 - The calculator assumes all rides are arriving or departing from the following locations:
 *   a) 30th Street Station
 *   b) Suburban Station
 *   c) Jefferson Station
 *
 * #2 - Station Kiosk is equivalent to advance purchase
 *
 * #3 - The widget is simply informative and does not take payments
 *
 * #4 - Anytime tickets can be only be purchased in bundles of 10.
 *
 * #5 - Responsiveness was not necessary. I'll be more than happy to go
 *  over how I would go about making the widget responsive. However, I thought it was
 *  best to allocate my time in understanding the requirements to better build the widget.
 *
 */

/**
 * ********************
 *   THANK YOU :)
 * ********************
 *
 * Thank you so much for taking the time to review this code.
 * I'm really excited about this opportunity and I hope to be
 * a part of your team one day.
 *
 */

const Home = () => {
  return (
    <>
      <Head>
        <title>SEPTA Regional Rail Fare Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContainer>
        <FairWidget />
      </MainContainer>
    </>
  );
};

export default Home;
